//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuksekogretim_Yonetim_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public int NotID { get; set; }
        public int OgrID { get; set; }
        public string Ders { get; set; }
        public Nullable<short> Vize1 { get; set; }
        public Nullable<short> Vize2 { get; set; }
        public Nullable<short> Final1 { get; set; }
        public Nullable<short> Final2 { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
