//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuksekogretim_Yonetim_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public int OgrID { get; set; }
        public int OgrNo { get; set; }
        public string OgrAdi { get; set; }
        public string OgrSoyAdi { get; set; }
        public string OgrDogumT { get; set; }
        public string OgrKayitT { get; set; }
        public string OgrTel { get; set; }
        public string OgrMail { get; set; }
        public string OgrAdres { get; set; }
        public string OgrUniversite { get; set; }
        public string OgrFakulte { get; set; }
        public string OgrBolum { get; set; }
        public string OgrSifre { get; set; }
        public string OgrFoto { get; set; }
    }
}
