//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuksekogretim_Yonetim_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonelID { get; set; }
        public int KatagoriId { get; set; }
        public int PersonelNo { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public string PersonelDogumT { get; set; }
        public string PersonelKayitT { get; set; }
        public string PersonelTel { get; set; }
        public string PersonelAdres { get; set; }
        public string PersonelMail { get; set; }
        public string PersonelUniversite { get; set; }
        public string PersonelFakulte { get; set; }
        public string PersonelBolum { get; set; }
        public string PersonelSifre { get; set; }
        public string PersonelFoto { get; set; }
    }
}
