//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuksekogretim_Yonetim_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class universiteler
    {
        public int uni_id { get; set; }
        public string uni_ad { get; set; }
        public int il_id { get; set; }
        public int status { get; set; }
    }
}
